### PR TITLE
README.md - mention and link to C++ directory

### PR DESCRIPTION
**Pull request by nyh**
Signed-off-by: Nadav Har'El <nyh@scylladb.com>

### CODE REVIEW

**Review by psarna — APPROVED** [review]

**Comment by psarna** [comment]
I'd commit, but I see that I don't have write rights to the repo (:

**Comment by nyh** [comment]
@avikivity do you know how come @psarna can't commit to the alternator-load-balancing repository? Don't all the maintainers have write permissions to it? I can't seem to configure the maintainers myself - I don't have permissions to do *that*...

**Comment by avikivity** [comment]
In fact only you had permissions. I adjusted it to all maintainers.

**Comment by nyh** [comment]
@avikivity thanks.

**Pull request closed without merging**
